# Generated by Django 5.0.2 on 2024-03-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
